name: Sync issue templates
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT_FOR_SYNC }}
          COMMIT_PREFIX: '[no ci]'
          PR_LABELS: false
          BRANCH_PREFIX: sync-issue-templates
